// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Dal.Context;

#nullable disable

namespace StoreApp.DalSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreApp.Dal.Entities.BillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BillNumber")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ItemTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PartyId")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Bill", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillNumber = 111,
                            Discount = 0.0m,
                            ItemTotal = 60.0m,
                            NetAmount = 60.0m,
                            PartyId = 3
                        },
                        new
                        {
                            Id = 2,
                            BillDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillNumber = 222,
                            Discount = 10.0m,
                            ItemTotal = 30.0m,
                            NetAmount = 130.0m,
                            PartyId = 2
                        },
                        new
                        {
                            Id = 3,
                            BillDate = new DateTime(2023, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillNumber = 333,
                            Discount = 20.0m,
                            ItemTotal = 180.0m,
                            NetAmount = 160.0m,
                            PartyId = 1
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.BillItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("BillId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Quantity")
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ItemId");

                    b.ToTable("BillItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40m,
                            BillId = 2,
                            ItemId = 1,
                            Price = 10.0m,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            BillId = 2,
                            ItemId = 2,
                            Price = 20.0m,
                            Quantity = 5m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 60m,
                            BillId = 1,
                            ItemId = 3,
                            Price = 30.0m,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 80m,
                            BillId = 3,
                            ItemId = 4,
                            Price = 40.0m,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100m,
                            BillId = 3,
                            ItemId = 5,
                            Price = 50.0m,
                            Quantity = 2m
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.DeliveryScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillItemId");

                    b.ToTable("DeliverySchedule", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillItemId = 1,
                            DeliveryDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 2,
                            BillItemId = 2,
                            DeliveryDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 3,
                            BillItemId = 2,
                            DeliveryDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 4,
                            BillItemId = 3,
                            DeliveryDate = new DateTime(2023, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 5,
                            BillItemId = 4,
                            DeliveryDate = new DateTime(2023, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 6,
                            BillItemId = 5,
                            DeliveryDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2m
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UnitId");

                    b.ToTable("Item", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0m,
                            LocationId = 5,
                            Name = "Apple",
                            Price = 0.5m,
                            Quantity = 0m,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0m,
                            LocationId = 3,
                            Name = "Banana",
                            Price = 0.3m,
                            Quantity = 0m,
                            UnitId = 5
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0m,
                            LocationId = 2,
                            Name = "Orange Juice",
                            Price = 1.5m,
                            Quantity = 0m,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0m,
                            LocationId = 1,
                            Name = "Milk",
                            Price = 0.8m,
                            Quantity = 0m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0m,
                            LocationId = 4,
                            Name = "Bread",
                            Price = 1.0m,
                            Quantity = 0m,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LocationRowId")
                        .HasColumnType("int");

                    b.Property<int>("RackNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUsingOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationRowId");

                    b.ToTable("Location", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First Floor",
                            LocationRowId = 4,
                            RackNo = 1,
                            StartedUsingOn = new DateTime(2025, 8, 19, 17, 9, 38, 816, DateTimeKind.Local).AddTicks(5810)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second Floor",
                            LocationRowId = 3,
                            RackNo = 1,
                            StartedUsingOn = new DateTime(2025, 8, 19, 17, 9, 38, 816, DateTimeKind.Local).AddTicks(5821)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third Floor",
                            LocationRowId = 2,
                            RackNo = 1,
                            StartedUsingOn = new DateTime(2025, 8, 19, 17, 9, 38, 816, DateTimeKind.Local).AddTicks(5829)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fourth Floor",
                            LocationRowId = 5,
                            RackNo = 1,
                            StartedUsingOn = new DateTime(2025, 8, 19, 17, 9, 38, 816, DateTimeKind.Local).AddTicks(5835)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fifth Floor",
                            LocationRowId = 1,
                            RackNo = 1,
                            StartedUsingOn = new DateTime(2025, 8, 19, 17, 9, 38, 816, DateTimeKind.Local).AddTicks(5842)
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.LocationRowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("LocationRow", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InUse = true,
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            InUse = false,
                            Name = "Second"
                        },
                        new
                        {
                            Id = 3,
                            InUse = false,
                            Name = "Third"
                        },
                        new
                        {
                            Id = 4,
                            InUse = false,
                            Name = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            InUse = false,
                            Name = "Fifth"
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.PartyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Party", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Elm St",
                            Email = "john@gamil.com",
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St",
                            Email = "jane@gmail.com",
                            Name = "Jane Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St",
                            Email = "acme@hmail.com",
                            Name = "Acme Corp",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Maple St",
                            Email = "global@gmail.com",
                            Name = "Global Industries",
                            PhoneNumber = "444-987-6543"
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Liter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milliliter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Piece"
                        });
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.BillEntity", b =>
                {
                    b.HasOne("StoreApp.Dal.Entities.PartyEntity", "Party")
                        .WithMany("Bills")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.BillItemEntity", b =>
                {
                    b.HasOne("StoreApp.Dal.Entities.BillEntity", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("StoreApp.Dal.Entities.ItemEntity", "Item")
                        .WithMany("BillItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.DeliveryScheduleEntity", b =>
                {
                    b.HasOne("StoreApp.Dal.Entities.BillItemEntity", "BillItem")
                        .WithMany("DeliverySchedules")
                        .HasForeignKey("BillItemId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("BillItem");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.ItemEntity", b =>
                {
                    b.HasOne("StoreApp.Dal.Entities.LocationEntity", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreApp.Dal.Entities.UnitEntity", "Unit")
                        .WithMany("Items")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.LocationEntity", b =>
                {
                    b.HasOne("StoreApp.Dal.Entities.LocationRowEntity", "LocationRow")
                        .WithMany("Locations")
                        .HasForeignKey("LocationRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationRow");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.BillEntity", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.BillItemEntity", b =>
                {
                    b.Navigation("DeliverySchedules");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.ItemEntity", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.LocationEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.LocationRowEntity", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.PartyEntity", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("StoreApp.Dal.Entities.UnitEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
